"""Generate the Clustering Mathematics Reference (.docx) for Phase 4.

One self-contained study document: for every method in src/clustering.py it gives the formula, a
plain-language explanation, a small WORKED numerical example, and the real number we observed in this
project. Run with SYSTEM python3 (which has python-docx; the .venv does not):

    /usr/bin/python3 planning/docs/generate_math_reference.py

This is a standalone reference -- NOT regenerated by _generate_docs.py (the numbered design docs).
"""
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

d = Document()

# Base style
normal = d.styles["Normal"]
normal.font.name = "Calibri"
normal.font.size = Pt(11)

BLUE = RGBColor(0x1F, 0x4E, 0x79)
GREY = RGBColor(0x60, 0x60, 0x60)


def h1(t):
    h = d.add_heading(t, level=1)
    h.runs[0].font.color.rgb = BLUE


def h2(t):
    d.add_heading(t, level=2)


def para(t):
    return d.add_paragraph(t)


def lead(label, t):
    p = d.add_paragraph()
    r = p.add_run(label + " ")
    r.bold = True
    r.font.color.rgb = BLUE
    p.add_run(t)
    return p


def formula(t):
    p = d.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.35)
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(2)
    r = p.add_run(t)
    r.font.name = "Cambria Math"
    r.font.size = Pt(12)
    return p


def example(lines):
    p = d.add_paragraph()
    r = p.add_run("Worked example")
    r.bold = True
    r.italic = True
    r.font.color.rgb = RGBColor(0xB0, 0x40, 0x30)
    for ln in lines:
        lp = d.add_paragraph()
        lp.paragraph_format.left_indent = Inches(0.35)
        lp.paragraph_format.space_after = Pt(0)
        rr = lp.add_run(ln)
        rr.font.name = "Consolas"
        rr.font.size = Pt(10)


def project(t):
    p = d.add_paragraph()
    p.paragraph_format.left_indent = Inches(0.15)
    r = p.add_run("In our project:  ")
    r.bold = True
    r.font.color.rgb = RGBColor(0x2C, 0x7A, 0x2C)
    rr = p.add_run(t)
    rr.italic = True


def bullet(t):
    d.add_paragraph(t, style="List Bullet")


def figref(t):
    p = d.add_paragraph()
    r = p.add_run("Figure: " + t)
    r.italic = True
    r.font.color.rgb = GREY
    r.font.size = Pt(9.5)


# =========================================================================== TITLE
title = d.add_heading("Clustering Mathematics Reference", level=0)
sub = d.add_paragraph("Phase 4 — Customer Segmentation Project  ·  the math behind src/clustering.py")
sub.runs[0].italic = True
sub.runs[0].font.color.rgb = GREY

para("This document explains every method used to find and validate the customer segments. Each "
     "entry has: the FORMULA, a plain explanation, a small WORKED EXAMPLE you can follow by hand, and "
     "the actual number we observed on the data. Teaching figures referenced here live in "
     "reports/figures/teaching/.")

lead("Notation.", "")
bullet("x_i ∈ R^d  — one customer as a d-dimensional vector (here d = 4: scaled Recency, Frequency, "
       "Monetary, Tenure).")
bullet("n — number of customers;  K — number of clusters;  C_k — the set of customers in cluster k.")
bullet("μ_k — centroid (mean vector) of cluster k;  μ — the overall mean of all customers.")
bullet("‖a − b‖² — squared Euclidean distance = Σ over dimensions of (a − b)².")

# =========================================================================== PART A
h1("Part A — The three clustering algorithms")
para("All three rest on one quantity, the within-cluster sum of squares (WCSS), seen three ways: "
     "K-Means minimises it directly, Ward minimises its increase greedily, and GMM generalises it to "
     "a probability model.")

# ---- K-Means
h2("A1. K-Means  (fit_kmeans)")
lead("What it answers.", "Partition customers into K groups so each is as tight as possible; the K "
     "centroids are the 'representative customers'.")
lead("Objective (minimise WCSS / inertia):", "")
formula("J = Σ_k Σ_{x ∈ C_k} ‖x − μ_k‖²        with   μ_k = (1/|C_k|) Σ_{x ∈ C_k} x")
para("The centroid μ_k is exactly the minimiser of the sum of squared distances within a cluster "
     "(set the derivative Σ 2(x − μ) = 0 → μ = mean). model.inertia_ stores J.")
lead("Algorithm (Lloyd, an EM-style alternation).", "")
formula("E-step (assign):  c(x) = argmin_k ‖x − μ_k‖²")
formula("M-step (update):  μ_k = mean of the points currently assigned to k")
para("Each step cannot increase J, and J ≥ 0, so the loop converges to a LOCAL minimum. Because it is "
     "non-convex, we restart n_init=10 times (k-means++ seeding) and keep the lowest-J run.")
example([
    "Data (1-D): x = [1, 2, 10, 11],  K = 2,  init μ1=1, μ2=2",
    "E: assign by nearest -> {1}|{2,10,11}      M: μ1=1, μ2=(2+10+11)/3=7.67",
    "E: assign -> {1,2}|{10,11}                 M: μ1=1.5, μ2=10.5",
    "E: no change -> CONVERGED. Clusters {1,2},{10,11}",
    "Inertia J = (0.25+0.25) + (0.25+0.25) = 1.0",
])
lead("Assumptions / cost.", "Voronoi cells → assumes convex, spherical, similar-size clusters; "
     "O(n·K·d·iters) (scales linearly).")
project("fit at K=2..8 to choose; deployed at K=3, inertia 2132.7; converged in 12 iterations on the "
        "real data.")
figref("kmeans_lloyd.png — the E/M iterations and the monotone inertia drop.")

# ---- GMM
h2("A2. Gaussian Mixture Model  (fit_gmm)")
lead("What it answers.", "Same goal, but SOFT: each customer is a probabilistic blend of K Gaussian "
     "'types', so we can detect boundary (fence-sitter) customers.")
lead("The model (a mixture of K Gaussians):", "")
formula("p(x) = Σ_k π_k · N(x | μ_k, Σ_k),     π_k ≥ 0,  Σ_k π_k = 1")
formula("N(x|μ,Σ) = (2π)^(−d/2) |Σ|^(−1/2) exp( −½ (x−μ)ᵀ Σ⁻¹ (x−μ) )")
para("π_k = segment size (mixing weight); μ_k = archetype; Σ_k = the oval's shape/size/tilt (this is "
     "what frees GMM from K-Means' circles). The exponent is the squared Mahalanobis distance.")
lead("Fit by EM (maximise the log-likelihood ℓ = Σ_i log Σ_k π_k N(x_i|μ_k,Σ_k)).", "")
formula("E-step (responsibility = posterior membership, by Bayes):")
formula("   γ_ik = π_k N(x_i|μ_k,Σ_k) / Σ_j π_j N(x_i|μ_j,Σ_j)")
formula("M-step (weighted MLE, with soft counts N_k = Σ_i γ_ik):")
formula("   π_k = N_k/n     μ_k = (1/N_k) Σ_i γ_ik x_i")
formula("   Σ_k = (1/N_k) Σ_i γ_ik (x_i−μ_k)(x_i−μ_k)ᵀ")
para("EM never decreases ℓ → converges to a local maximum (hence n_init restarts).")
example([
    "Two components, point x.  π = [0.5, 0.5]",
    "N(x|comp1) = 0.05,  N(x|comp2) = 0.15",
    "γ1 = 0.5·0.05 / (0.5·0.05 + 0.5·0.15) = 0.025/0.10 = 0.25",
    "γ2 = 0.75   ->  x is 25% type-1, 75% type-2 (a soft membership)",
])
lead("Link to K-Means.", "Fix Σ_k = σ²I and let σ² → 0: responsibilities become hard (argmax) and the "
     "μ_k update becomes the K-Means mean. So K-Means = hard, spherical, zero-variance GMM.")
lead("covariance_type & parameters.", "spherical (K params) · diag (Kd) · tied (d(d+1)/2) · full "
     "(K·d(d+1)/2). More params = more flexible but overfit-prone; chosen by BIC.")
lead("Singularity (failure mode).", "If a component collapses onto a few points, Σ_k → 0, density → ∞, "
     "ℓ → ∞ — unbounded likelihood. Guarded by reg_covar (adds εI).")
project("at K=3 (full covariance) GMM diverged most from K-Means (ARI 0.38) — it places overlapping "
        "ovals; only 4.3% of customers were fence-sitters (max γ < 0.6).")
figref("gmm_em.png — soft-membership colour blend + covariance ellipses stretching each M-step.")

# ---- Ward
h2("A3. Ward agglomerative (hierarchical)  (fit_ward)")
lead("What it answers.", "Build a family tree of customers by repeatedly merging the two most similar "
     "groups; cut the tree at K leaves. Gives the dendrogram narrative.")
lead("Ward's merge criterion (merge the pair that adds least WCSS):", "")
formula("Δ(A,B) = ( |A|·|B| / (|A|+|B|) ) · ‖μ_A − μ_B‖²")
para("Δ is exactly the increase in within-cluster SS when A and B fuse — so Ward greedily optimises "
     "the SAME objective as K-Means, but hierarchically and irreversibly.")
lead("Lance–Williams recurrence (O(1) distance update after a merge):", "")
formula("d(A∪B, C) = [ (n_A+n_C)d(A,C) + (n_B+n_C)d(B,C) − n_C d(A,B) ] / (n_A+n_B+n_C)")
example([
    "A = {(0,0)}, B = {(2,0)}  (singletons, distance 2 apart)",
    "Δ(A,B) = (1·1/2) · ‖(0,0)−(2,0)‖² = 0.5 · 4 = 2.0   (adds 2 to WCSS)",
    "C = {(0,1),(0,-1)}, centroid (0,0):",
    "Δ(A,C) = (1·2/3) · ‖(0,0)−(0,0)‖² = 0   (merging at same centroid is free)",
])
lead("Cost.", "O(n²) memory for the proximity structure (~140 MB at n=4234); greedy/irreversible.")
project("at K=3, Ward agreed with K-Means (ARI 0.61); cophenetic correlation 0.54 (weak tree → "
        "gradient, not crisp hierarchy).")
figref("(dendrogram in 04b_method_comparison: reports/figures/04b_method_comparison/dendrogram.png)")

# =========================================================================== PART B
h1("Part B — Choosing K (scoring)")

h2("B1. Inertia & the elbow / knee  (knee_point)")
lead("Idea.", "Inertia J(K) always falls with K (hits 0 at K=n) so it can't be minimised — find the "
     "'bend'. We make the bend objective: normalise both axes to [0,1], draw the chord between the "
     "endpoints, and pick K of MAXIMUM vertical gap below the chord.")
formula("knee = argmax_K [ chord(K) − inertia_norm(K) ]")
example([
    "K:        2     3     4     5",
    "inertia:  100   55    45    40   (normalised, chord from K2→K5)",
    "gap below chord is largest at K=3  ->  knee = 3",
])
project("knee landed at K=4 (a gentle elbow — part of the 3-vs-4 ambiguity).")
figref("internal_indices.png panel (B) — the chord and the red gap segments.")

h2("B2. Silhouette  (sweep_k)")
lead("Per-customer cohesion vs separation:", "")
formula("a(i) = mean dist from i to its OWN cluster")
formula("b(i) = min over other clusters of (mean dist from i to that cluster)")
formula("s(i) = ( b(i) − a(i) ) / max( a(i), b(i) )   ∈ [−1, 1]")
para("s≈+1 deep inside; s≈0 on a boundary; s<0 likely mis-assigned. Average over customers = one "
     "score per K. Calibration: >0.7 strong, 0.5–0.7 reasonable, 0.25–0.5 weak, <0.25 none.")
example([
    "Customer i: a(i)=2 (tight to own cluster), b(i)=5 (far from nearest other)",
    "s(i) = (5 − 2) / max(2,5) = 3/5 = 0.60   (comfortably inside its cluster)",
])
project("peaked at K=3 with mean silhouette 0.367 — 'weak but normal' for behavioural RFM.")
figref("internal_indices.png panel (A) — per-point silhouette anatomy.")

h2("B3. Calinski–Harabasz  (sweep_k)")
formula("CH = [ tr(B)/(K−1) ] / [ tr(W)/(n−K) ],   tr(B)=Σ_k n_k‖μ_k−μ‖²,  tr(W)=inertia")
para("A variance ratio (between ÷ within), like an ANOVA F-statistic; HIGHER is better. The (K−1), "
     "(n−K) terms penalise more clusters. Spherical-biased → corroborates, not decides.")
project("peaked at K=3 (CH = 2944).")

h2("B4. Davies–Bouldin  (sweep_k)")
formula("s_i = mean dist of cluster i's points to its centroid")
formula("R_ij = (s_i + s_j) / d(c_i, c_j);   DB = (1/K) Σ_i max_{j≠i} R_ij")
para("Each cluster's worst-case overlap with a neighbour, averaged; LOWER is better.")
example([
    "Two clusters: spreads s1=1.0, s2=1.5, centroid distance d=5",
    "R12 = (1.0 + 1.5)/5 = 0.5  ->  DB = 0.5",
])
project("minimum at K=4 (DB = 0.969) — the other half of the 3-vs-4 split.")

h2("B5. Gap statistic  (gap_statistic, gap_choice)")
lead("Idea.", "Compare your clustering's tightness to clustering pure RANDOM data of the same spread.")
formula("Gap(k) = E_null[ log W_k* ] − log W_k,      W_k = inertia (pooled WCSS)")
formula("s_k = sd(log W_k*) · √(1 + 1/B)        (B = number of null datasets)")
lead("Selection rule (built-in Occam's razor):", "")
formula("smallest k such that  Gap(k) ≥ Gap(k+1) − s_{k+1}")
para("Uniquely, the gap statistic CAN return k=1 = 'no real clusters'. The null is a uniform sample "
     "in the data's (PCA-rotated) bounding box.")
example([
    "From our data:  Gap(1)=1.488,  Gap(2)=1.449,  s_2=0.008",
    "Rule at k=1:  1.488 ≥ 1.449 − 0.008 = 1.441 ?  YES  ->  choose k=1",
    "Meaning: no crisp cluster count — a continuum.",
])
project("Gap → K=1 when K=1 is allowed (its 'no clusters' verdict). Excluding K=1 makes it rise "
        "monotonically and fall back to the max — which is why we run it from K=1.")
figref("gap_statistic.png — null vs real scatter, log W curves, and Gap(k) ± s_k.")

h2("B6. GMM BIC  (gmm_bic)")
formula("BIC = −2ℓ + p·ln(n)        (ℓ = max log-likelihood, p = # free params)")
para("Lower is better; the ln(n) penalty (harsher than AIC's 2p) discourages extra components. For "
     "FULL covariance: p = K·d (means) + K·d(d+1)/2 (covariances) + (K−1) (weights).")
example([
    "Full covariance, d=4, K=3, n=4234:",
    "p = 3·4 + 3·(4·5/2) + 2 = 12 + 30 + 2 = 44",
    "penalty = p·ln(n) = 44 · ln(4234) = 44 · 8.351 = 367.4",
    "vs misfit −2ℓ ≈ 12073  ->  penalty is tiny, so BIC chases fit -> high K",
])
lead("Why it over-selects.", "The complexity penalty is small next to the likelihood scale, and GMM "
     "singularities hand out 'free' likelihood at high K → BIC can prefer an over-fit K.")
project("BIC 'wanted' K=8 (diag covariance hit −209 — a singularity), so we discounted it.")
figref("bic_anatomy.png — BIC by covariance type, and the −2ℓ vs p·ln n trade-off.")

# =========================================================================== PART C
h1("Part C — Validation (is it real?)")

h2("C1. Bootstrap Jaccard stability  (bootstrap_stability)")
lead("Idea.", "Real structure reproduces under perturbation; artifacts dissolve.")
formula("Jaccard:  J(A,B) = |A ∩ B| / |A ∪ B|   ∈ [0,1]")
para("Cluster the full data (reference). Repeat ~100×: subsample 80% WITHOUT replacement, re-cluster, "
     "match each reference cluster to its best-Jaccard bootstrap cluster (on shared customers); "
     "average. Bands: >0.85 highly stable, 0.75–0.85 stable, 0.60–0.75 suggestive, <0.60 dissolves.")
example([
    "A = {1,2,3,4} (reference cluster),  B = {3,4,5} (bootstrap cluster)",
    "J = |{3,4}| / |{1,2,3,4,5}| = 2/5 = 0.40",
])
para("Without replacement avoids duplicate points (distance 0 → fake micro-clusters). Per-cluster "
     "scoring catches '3 solid + 1 dissolving' (a sign K is too high).")
project("all 3 clusters ≈ 0.79 (stable, none dissolving) — this broke the 3-vs-4 tie toward K=3.")
figref("stability.png panel (A).")

h2("C2. Consensus matrix  (consensus_matrix)")
formula("M_ij = (# runs i,j in SAME cluster) / (# runs i,j BOTH sampled)")
para("Reordered by cluster, the right K gives a near block-diagonal matrix (entries near 0 or 1). "
     "Crispness = 1 − 2·mean(min(M, 1−M)); 1 = perfectly crisp, 0 = all ambiguous.")
example([
    "Pair (i,j): both sampled in 20 runs, same cluster in 18 of them",
    "M_ij = 18/20 = 0.90  (they almost always cluster together)",
])
project("crispness 0.97 at K=3 vs 0.90 at over-split K=8 — blocks smear when over-split.")
figref("stability.png panels (B) good K vs (C) over-split K.")

h2("C3. Adjusted Rand Index  (ari_matrix)")
lead("Idea.", "How much do two labelings agree on which customers belong together — corrected for "
     "chance, and immune to the arbitrary cluster numbers (label-invariant).")
formula("ARI = ( RI − E[RI] ) / ( max RI − E[RI] )")
para("RI counts customer PAIRS the two labelings agree on (both-together or both-apart) over all "
     "pairs; E[RI] is the value expected at random. ARI = 1 identical, 0 chance-level, <0 worse than "
     "random. Computed from the contingency table of overlaps n_ij with row/col sums a_i, b_j:")
formula("ARI = ( Σ_ij C(n_ij,2) − [Σ_i C(a_i,2)·Σ_j C(b_j,2)]/C(n,2) ) /")
formula("      ( ½[Σ_i C(a_i,2)+Σ_j C(b_j,2)] − [Σ_i C(a_i,2)·Σ_j C(b_j,2)]/C(n,2) )")
example([
    "Two identical partitions of n customers  ->  every pair agrees  ->  ARI = 1.",
    "A random relabelling  ->  ARI ≈ 0 (chance agreement is subtracted off).",
])
project("the headline 3×3 ARI: K-Means↔Ward 0.61, GMM 0.38/0.27 — moderate, not unanimous → a "
        "continuum (cores agree, boundaries differ).")
figref("(04b_method_comparison: reports/figures/04b_method_comparison/ari_matrix.png)")

h2("C4. Cophenetic correlation  (cophenetic_corr)")
formula("coph = corr( d_ij , c_ij )")
para("d_ij = original distance between customers i,j; c_ij = the dendrogram 'merge height' at which "
     "i and j first land in the same cluster. Correlation > 0.7 means the tree faithfully represents "
     "the real distances (so reading a cut off it is trustworthy).")
project("0.54 — a weak tree, confirming the data is a gradient, not a clean hierarchy.")

h2("C5. PCA projection  (pca_2d)")
lead("Idea.", "Rotate to the directions of greatest variance so we can plot 4-D customers in 2-D "
     "(and overlay each method's labels on the SAME coordinates).")
formula("Centre X; covariance C = (1/n) XᵀX;  eigen-decompose C = V Λ Vᵀ")
formula("PCs = columns of V with largest eigenvalues;  explained ratio_k = λ_k / Σ_j λ_j")
para("Equivalently via SVD X = U Σ Vᵀ (the columns of V are the principal axes, σ² ∝ λ).")
example([
    "If eigenvalues λ = [3.0, 0.8, 0.15, 0.05] (sum 4.0):",
    "PC1 explains 3.0/4.0 = 75%, PC2 explains 0.8/4.0 = 20%  ->  86% in 2-D",
])
project("the 2-D PCA view underlies every scatter in the teaching figures and the 04b label overlays.")

# =========================================================================== CLOSE
h1("How it all fits together")
para("Choosing K is a JUDGEMENT triangulated across evidence that fails in DIFFERENT directions, so "
     "agreement is meaningful and disagreement is itself a finding:")
bullet("Internal indices (silhouette, CH, DB, elbow) NARROW K — here to 3–4.")
bullet("Principled indices (gap → K=1, BIC → K=8) sat at opposite extremes — both diagnosing a "
       "continuum (no crisp K), not real structure.")
bullet("Stability (bootstrap Jaccard, consensus) BROKE the tie — K=3 reproduced best.")
bullet("Cross-method ARI judged REALNESS — moderate agreement = a useful discretisation of a "
       "continuum, not natural kinds. We deploy K-Means at K=3 (+ the one-timer segment = 4 groups).")

d.save("planning/docs/Clustering_Mathematics_Reference.docx")
print("saved: planning/docs/Clustering_Mathematics_Reference.docx")
