"""Generate the CLV Mathematics Reference (.docx) for Phase 5.

One self-contained study document: for every piece of the CLV engine (src/clv.py) it gives the
formula, a plain explanation, a worked numerical example, and the real number observed in this
project. Run with SYSTEM python3 (which has python-docx; the .venv does not):

    /usr/bin/python3 planning/docs/generate_clv_math_reference.py

Standalone reference — NOT regenerated by _generate_docs.py (the numbered design docs).
"""
from docx import Document
from docx.shared import Pt, Inches, RGBColor

d = Document()
normal = d.styles["Normal"]
normal.font.name = "Calibri"
normal.font.size = Pt(11)
BLUE = RGBColor(0x1F, 0x4E, 0x79)
GREY = RGBColor(0x60, 0x60, 0x60)


def h1(t):
    h = d.add_heading(t, level=1); h.runs[0].font.color.rgb = BLUE


def h2(t):
    d.add_heading(t, level=2)


def para(t):
    return d.add_paragraph(t)


def lead(label, t):
    p = d.add_paragraph(); r = p.add_run(label + " "); r.bold = True; r.font.color.rgb = BLUE
    p.add_run(t); return p


def formula(t):
    p = d.add_paragraph(); p.paragraph_format.left_indent = Inches(0.35)
    p.paragraph_format.space_before = Pt(2); p.paragraph_format.space_after = Pt(2)
    r = p.add_run(t); r.font.name = "Cambria Math"; r.font.size = Pt(12)
    return p


def example(lines):
    p = d.add_paragraph(); r = p.add_run("Worked example"); r.bold = True; r.italic = True
    r.font.color.rgb = RGBColor(0xB0, 0x40, 0x30)
    for ln in lines:
        lp = d.add_paragraph(); lp.paragraph_format.left_indent = Inches(0.35)
        lp.paragraph_format.space_after = Pt(0)
        rr = lp.add_run(ln); rr.font.name = "Consolas"; rr.font.size = Pt(10)


def project(t):
    p = d.add_paragraph(); p.paragraph_format.left_indent = Inches(0.15)
    r = p.add_run("In our project:  "); r.bold = True; r.font.color.rgb = RGBColor(0x2C, 0x7A, 0x2C)
    rr = p.add_run(t); rr.italic = True


def bullet(t):
    d.add_paragraph(t, style="List Bullet")


def figref(t):
    p = d.add_paragraph(); r = p.add_run("Figure: " + t); r.italic = True
    r.font.color.rgb = GREY; r.font.size = Pt(9.5)


# =========================================================================== TITLE
d.add_heading("CLV Mathematics Reference", level=0)
sub = d.add_paragraph("Phase 5 — Customer Segmentation Project  ·  the math behind src/clv.py")
sub.runs[0].italic = True; sub.runs[0].font.color.rgb = GREY

para("Customer Lifetime Value = how much a customer will be worth over a future window. It splits "
     "into two forecasts that we multiply: HOW MANY times will they buy (BG/NBD) × HOW MUCH per "
     "purchase (Gamma-Gamma). This document gives the formula, a plain explanation, a worked example, "
     "and the real project number for each. Figures referenced live in reports/figures/05_clv/.")

lead("The two-track principle (doc 12).", "CLV is built from Recency/Frequency/Monetary — the same "
     "signals clustering uses — so it must NOT be a clustering input (that would double-count spend). "
     "We build segments from behaviour, then state what each segment is worth. Keeping them separate "
     "also buys a free validation: if high-CLV customers concentrate in one behavioural segment, two "
     "independent methods agree.")

lead("The naming trap (doc 15).", "CLV inputs share names with clustering features but mean different "
     "things: frequency = number of REPEAT purchase occasions (a one-time buyer = 0); recency = age "
     "at last purchase t_x = (last − first); T = customer age = (anchor − first); monetary_value = "
     "average value of REPEAT transactions. Built by features.build_clv_inputs via rfm_summary.")

# =========================================================================== PART A — BG/NBD
h1("Part A — BG/NBD (how many future purchases + P(alive))")
para("Retail is NON-CONTRACTUAL: customers never announce they have left, they just stop buying. "
     "BG/NBD infers churn probabilistically from two hidden processes per customer.")

h2("A1. Process 1 — buying while alive (the NBD)")
lead("Story.", "While ALIVE, a customer buys as a Poisson process at their own rate λ (purchases per "
     "unit time — memoryless, no schedule). Rates differ across people, drawn from a Gamma.")
formula("buys in time t  ~  Poisson(λ t)          λ  ~  Gamma(r, α)")
para("Poisson counts + Gamma heterogeneity across the population = a Negative Binomial distribution "
     "of purchase counts (the 'NBD'). The Gamma's mean rate is r/α.")
example([
    "Fitted r = 0.64, α = 62  ->  mean λ = r/α = 0.64/62 = 0.0103 per DAY",
    "                            = 0.0103 × 365 ≈ 3.74 purchases per YEAR",
    "Most customers buy a few times/yr; a long tail buys often (the Gamma shape).",
])
project("r = 0.635, α = 61.96 (MAP). See the Gamma curve in bgnbd_outputs.png panel A.")

h2("A2. Process 2 — dropping out (the BG)")
lead("Story.", "After EACH purchase the customer flips a coin: with probability p they go inactive "
     "forever (die); with prob (1−p) they buy again. p differs across people, drawn from a Beta.")
formula("purchases until death  ~  Geometric(p)          p  ~  Beta(a, b)")
para("The Beta's mean dropout probability is a/(a+b). Four population parameters (r, α, a, b) are fit "
     "from everyone's (frequency, recency, T) by MAP or MCMC — no per-customer tuning.")
example([
    "Fitted a = 0.15, b = 2.76  ->  mean dropout p = a/(a+b) = 0.15/2.91 = 0.052",
    "i.e. ~5% chance of quitting after any given purchase (most customers are fairly loyal).",
])
project("a = 0.150, b = 2.762 (MAP). Beta curve in bgnbd_outputs.png panel B.")

h2("A3. The magic output — P(alive)")
lead("What it is.", "Given a customer's (frequency x, recency t_x, age T), the model returns the "
     "posterior probability they are still active.")
formula("P(alive | x, t_x, T)  =  posterior from combining the NBD + BG processes")
para("Intuition: a long silence is SURPRISING relative to a customer's own established rate. A "
     "once-frequent buyer who has gone quiet → low P(alive); a naturally rare buyer who is quiet → "
     "still high P(alive). THIS is why recency drives churn, not raw frequency.")
example([
    "Two customers, both silent for 200 days:",
    "  A bought 50× at a fast pace  -> 200-day silence is alarming -> P(alive) LOW",
    "  B bought 2× slowly           -> 200-day silence is normal   -> P(alive) high",
])
project("mean P(alive) = 0.89; only 2.7% below the 0.3 churn-risk line.")
figref("bgnbd_brain.png — P(alive) and expected purchases over the (frequency, recency) grid.")

h2("A4. Forecast — expected future purchases")
formula("E[ purchases in next t ]  =  closed form using the Gaussian hypergeometric function")
para("Used over the CLV horizon (12 months ≈ 365 days). One number per customer.")
project("mean expected purchases next 12 mo = 2.82 (median 1.57).")

# =========================================================================== PART B — Gamma-Gamma
h1("Part B — Gamma-Gamma (how much per purchase)")

h2("B1. The spend model + Bayesian shrinkage")
lead("Story.", "Each customer has a TRUE average spend per transaction; observed order values scatter "
     "(Gamma) around it. That per-customer mean itself varies across the population (also Gamma) → "
     "Gamma-Gamma, three parameters, fit on REPEAT buyers only (frequency > 0).")
lead("Shrinkage (the key behaviour).", "The predicted average spend is a precision-weighted blend of "
     "the customer's OWN observed average and the POPULATION mean:")
formula("ŝ_i  ≈  ( n_i · own_average  +  k · population_mean ) / ( n_i + k )      n_i = frequency")
para("Many transactions (large n) → trust their own average; few → pull toward the population. One "
     "£900 order is not proof of a £900 customer.")
example([
    "Population mean spend ≈ £404.",
    "Customer with ONE £10 order  -> thin evidence -> predicted pulled UP toward ~£200.",
    "Customer with 50 orders avg £10 -> rich evidence -> predicted stays ~£12 (own data).",
])
project("population mean £404; shrinkage visible as the S-curve in gamma_gamma_shrinkage.png "
        "(dark = low-frequency points deviate most toward £404).")

h2("B2. The validity gate (must pass BEFORE fitting)")
lead("Assumption.", "Gamma-Gamma assumes a customer's average spend is INDEPENDENT of how often they "
     "buy. If frequent buyers systematically spend more/less per order, the model is misapplied.")
formula("check  corr(frequency, monetary_value) ≈ 0   (|Pearson| < 0.30 rule of thumb)")
para("Pearson tests LINEAR independence (the formal assumption); Spearman (rank) is reported "
     "alongside for honesty.")
example([
    "Pearson = 0.021  -> < 0.30  -> PASSES.",
    "Spearman = 0.254 + binned medians £244→£418 -> a MILD monotonic creep, reported as a caveat.",
])
project("gate PASSES (Pearson 0.02) with a documented mild-monotonic caveat. See gamma_gamma_gate.png.")

# =========================================================================== PART C — CLV
h1("Part C — Combining into CLV")
formula("CLV  =  Σ over future periods  E[transactions] × E[value per transaction]  / (1+d)^period")
para("BG/NBD supplies the expected transactions, Gamma-Gamma the expected value; d is an optional "
     "yearly discount rate (DCF). Horizon = 12 months (doc 12). One-timers (frequency 0) get BG/NBD "
     "purchases × the population-mean spend (their Gamma-Gamma fallback).")
example([
    "A customer expected to buy 3× in the next 12 mo, at £150/order:",
    "  CLV(12 mo, undiscounted) = 3 × £150 = £450",
    "With 10% annual discounting the later months are worth slightly less (deferred to v2).",
])
project("mean 12-mo CLV £1,396, median £536, max £252k (a wholesaler). One-timer mean £311 vs "
        "repeat £1,831. Built-in vs manual (purchases×spend) agree within 1.3%. See clv_components.png.")

# =========================================================================== PART D — Validation
h1("Part D — Validation & uncertainty (doc 08)")

h2("D1. Temporal holdout (does it predict the FUTURE?)")
lead("Method.", "Split the timeline at a cutoff: fit BG/NBD on the CALIBRATION period (before), "
     "predict purchases in the HOLDOUT period (after), compare to what ACTUALLY happened. Repeat at "
     "3/6/9-month holdouts.")
formula("calibration plot:  for each calibration-frequency bin, mean predicted ≈ mean actual")
para("A well-calibrated model's predicted and actual curves overlap. Also check PARAMETER STABILITY "
     "(do r, α, a, b stay steady across cutoffs?).")
example([
    "3-mo holdout: total predicted / actual = 0.77 (under-predicts the Christmas run-up)",
    "6-mo holdout: 0.98 (near-perfect)        9-mo: 1.12 (over-predicts)",
    "Shape tracks well in all three -> customer RANKING is trustworthy.",
])
project("calibration shape excellent; a vertical bias = SEASONALITY (gift-ware Christmas peak), which "
        "a 12-month horizon averages out. calibration_small_multiples.png + parameter_stability.png.")

h2("D2. The trap — do NOT rank cutoffs by raw error")
para("Moving the cutoff changes TWO things at once: calibration length AND prediction horizon. A "
     "3-month holdout shows lower raw MAE simply because predicting 3 months is easier — NOT because "
     "it is a better model. Judge calibration + parameter stability (horizon-fair), not raw MAE.")

h2("D3. MAP vs MCMC (point estimate vs full uncertainty)")
lead("MAP.", "Maximum A Posteriori — the single most probable parameter values (the posterior peak). "
     "Fast (seconds). Output is a point estimate. Used while BUILDING.")
lead("MCMC.", "Draws thousands of samples from the FULL posterior. Slow (minutes). Output is a "
     "distribution → credible intervals, posterior predictive checks, R-hat/ESS diagnostics. Used for "
     "the FINAL deliverable.")
example([
    "Two customers, same point estimate £450:",
    "  A (20 purchases): MCMC £450, 90% CI [410, 490]  (tight — we trust it)",
    "  B (2 purchases):  MCMC £450, 90% CI [120, 980]  (wide — thin evidence)",
    "MAP gives both the SAME £450 and hides the difference; MCMC exposes it.",
])
project("Phase 5 built with MAP; the production fit (05b) uses MCMC for credible intervals.")

# =========================================================================== CLOSE
h1("How it all fits together")
bullet("Gate: confirm spend ⟂ frequency (Gamma-Gamma is valid).")
bullet("BG/NBD: expected future purchases + P(alive), from (frequency, recency, T).")
bullet("Gamma-Gamma: expected £/transaction, shrunk toward the population for thin-evidence customers.")
bullet("CLV = purchases × spend over 12 months; one-timers use the population-mean spend.")
bullet("Validate by temporal holdout (calibration + parameter stability), read honestly.")
bullet("Deliver with MCMC so every CLV carries a credible interval.")
bullet("Phase 6 joins CLV to the K=3 segments on Customer ID — the free cross-validation.")

d.save("planning/docs/CLV_Mathematics_Reference.docx")
print("saved: planning/docs/CLV_Mathematics_Reference.docx")
